registration-field-format /= "string"
registration-field-format /= "string_or_null"
registration-field-format /= "url"
registration-field-format /= "url_or_null"
registration-field-format /= "email"
registration-field-format /= "email_or_null"
registration-field-format /= "boolean"
registration-field-format /= "boolean_or_null"
registration-field-format /= "image"
registration-field-format /= "image_or_null"
registration-field-format /= "pdf"
registration-field-format /= "pdf_or_null"
